services:
  redis:
    image: redis:7-alpine
    container_name: marketinsight-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: marketinsight-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped